### PR TITLE
Interface redesign proposal

### PR DESCRIPTION
**Pull request by Miqueas**
Just a small contribution

### CODE REVIEW

**Comment by sodomon2** [comment]
@Miqueas You could remove the `ap` check since it does not need to be in the design.
ap

and could you redesign/organize this section? 

input

as it looks a bit... weird?

**Comment by Miqueas** [comment]
> @Miqueas You could remove the `ap` check since it does not need to be in the design.
> ap

No problem, I didn't know that

> input
> as it looks a bit... weird?

In what way you think looks weird? Tell me what you think and I'll try to fix it

**Comment by Miqueas** [comment]
Maybe you just want to separate settings like this?

image

**Comment by sodomon2** [comment]
> Maybe you just want to separate settings like this?
> 
> image

Exactly, now it looks much better because now it doesn't look like everything is in one box.

I like it a lot, so I will merge this :)

**Comment by Miqueas** [comment]
> Exactly, now it looks much better because now it doesn't look like everything is in one box.
> 
> I like it a lot, so I will merge this :)

Nice!

**Pull request merged**
